# Generated by Django 4.2.21 on 2025-05-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='This is a defult description', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='This is a default description', upload_to='articles/'),
            preserve_default=False,
        ),
    ]
