# Generated by Django 4.2.21 on 2025-06-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_description_article_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('book_title', models.CharField(max_length=200)),
                ('author', models.CharField(default='Unknown Author', max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('picture', models.ImageField(upload_to='bookreviews/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.ManyToManyField(blank=True, to='api.article')),
                ('book_reviews', models.ManyToManyField(blank=True, to='api.bookreview')),
            ],
        ),
    ]
