# Generated by Django 4.2.21 on 2025-06-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookreview_article_author_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ManyToManyField(blank=True, to='api.article')),
            ],
        ),
        migrations.CreateModel(
            name='BookReviewHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_review', models.ManyToManyField(blank=True, to='api.bookreview')),
            ],
        ),
        migrations.DeleteModel(
            name='Highlights',
        ),
    ]
