# Generated by Django 4.2.21 on 2025-06-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_articlehighlight_bookreviewhighlight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreviewhighlight',
            name='book_review',
        ),
        migrations.AddField(
            model_name='article',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ArticleHighlight',
        ),
        migrations.DeleteModel(
            name='BookReviewHighlight',
        ),
    ]
